#!/usr/bin/env python3
"""
This script is used to compress the output files generated by the ABCfold pipeline.

This script processes one or more tarballs (.tar.gz, .tar.xz) containing
the full output of an ABCfold run. For each tarball, it:
1. Extracts the contents to a temporary directory.
2. Runs the respective `extract_outputs.py` script for AlphaFold3, Boltz, and Chai1
   to generate a standardized, compressed set of outputs (structures, scores, etc.).
3. Copies important unique files (e.g., input JSON, MSA depth plot) to the output directory.
4. Saves logs of the extraction process.

The final output is organized by protein name in the specified output directory.
By default, structures, pLDDT, and PTM scores are extracted. Additional data
can be extracted using flags.

This version supports parallel processing of tarballs to improve throughput.
"""

import argparse
import concurrent.futures
import logging
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from typing import List, Tuple

from tqdm import tqdm

try:
    from tqdm import tqdm
except ImportError:
    # Fallback if tqdm not installed
    def tqdm(iterable, *args, **kwargs):
        return iterable

# Define paths to the model-specific extractor scripts
try:
    SCRIPT_DIR = pathlib.Path(__file__).parent.resolve()
    AF3_EXTRACTOR = SCRIPT_DIR.parent / "alphafold3" / "extract_outputs.py"
    BOLTZ_EXTRACTOR = SCRIPT_DIR.parent / "boltz" / "extract_outputs.py"
    CHAI1_EXTRACTOR = SCRIPT_DIR.parent / "chai1" / "extract_outputs.py"
    EXTRACTOR_SCRIPTS = [AF3_EXTRACTOR, BOLTZ_EXTRACTOR, CHAI1_EXTRACTOR]
except NameError:
    # For interactive environments where __file__ is not defined
    SCRIPT_DIR = pathlib.Path(".").resolve()
    AF3_EXTRACTOR, BOLTZ_EXTRACTOR, CHAI1_EXTRACTOR = None, None, None


def setup_logging(verbose: bool, log_file: pathlib.Path = None):
    """
    Set up logging for the script.
    - File handler: logs everything (DEBUG or INFO level)
    - Console handler: only logs errors
    """
    logger = logging.getLogger()
    logger.setLevel(logging.DEBUG)
    
    # Remove any existing handlers
    for handler in logger.handlers[:]:
        logger.removeHandler(handler)
    
    # Format for all messages
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    
    # Console handler: only ERROR level
    console_handler = logging.StreamHandler(sys.stderr)
    console_handler.setLevel(logging.ERROR)
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    
    # File handler: all messages (DEBUG if verbose, else INFO)
    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        file_log_level = logging.DEBUG if verbose else logging.INFO
        file_handler = logging.FileHandler(log_file, mode='w')
        file_handler.setLevel(file_log_level)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
        logging.info(f"Logging to file: {log_file}")


def find_tarballs(input_dirs: List[pathlib.Path]) -> List[pathlib.Path]:
    """Find all .tar.xz and .tar.gz files in the input directories."""
    tarballs = []
    for directory in input_dirs:
        if not directory.is_dir():
            logging.warning(f"Input path is not a directory, skipping: {directory}")
            continue
        logging.info(f"Searching for tarballs in: {directory}")
        for ext in ["*.tar.xz", "*.tar.gz"]:
            found = sorted(list(directory.glob(ext)))
            if found:
                logging.info(f"  Found {len(found)} '{ext}' files.")
                tarballs.extend(found)
    return tarballs


def get_protein_name_from_tarball(tarball_path: pathlib.Path) -> str:
    """
    Extract a clean protein name from the tarball filename by splitting on
    known delimiters or date pattern.
    
    Supported formats:
    - name_data_YYYYMMDD_HHMMSS_ms.tar.xz (splits on _data_)
    - name_af3_YYYYMMDD_HHMMSS_ms.tar.xz (splits on _af3_)
    - name_YYYYMMDD_HHMMSS_ms.tar.xz (splits on _YYYYMMDD pattern)
    """
    fname = tarball_path.name
    
    # Try explicit delimiters first
    if "_data_" in fname:
        protein_name = fname.split("_data_")[0]
    elif "_af3_" in fname:
        protein_name = fname.split("_af3_")[0]
    else:
        # Fallback: try to match date_time_ms pattern (_YYYYMMDD_HHMMSS_ms)
        # Pattern: _[8 digits]_[6 digits]_[1-3 digits]
        date_pattern = r'_(\d{8})_(\d{6})_(\d{1,3})\.tar'
        match = re.search(date_pattern, fname)
        
        if match:
            # Extract everything before the date pattern
            protein_name = fname[:match.start()]
            logging.info(
                f"Extracted protein name '{protein_name}' from '{fname}' "
                f"using date pattern (date: {match.group(1)}, time: {match.group(2)}, ms: {match.group(3)})"
            )
        else:
            # Final fallback: remove tar extension
            protein_name = fname.rsplit('.tar', 1)[0]
            logging.warning(
                f"Could not determine protein name from delimiters or date pattern in '{fname}'. "
                f"Using fallback name: '{protein_name}'"
            )
    return protein_name


def run_extractor(
    extractor_script: pathlib.Path,
    run_dir: pathlib.Path,
    output_dir: pathlib.Path,
    protein_name: str,
    args: argparse.Namespace,
    log_file: pathlib.Path
):
    """
    Run a model-specific extractor script using subprocess.

    Args:
        extractor_script: Path to the extractor script to run.
        run_dir: The temporary directory where tarball contents are extracted.
        output_dir: The main output directory for compressed results.
        protein_name: The name of the protein being processed.
        args: The command-line arguments namespace to check for flags.
        log_file: Path to the file for saving execution logs.
    """
    model_name = extractor_script.parent.name
    logging.info(f"Running {model_name} extractor for {protein_name}...")

    cmd = [
        sys.executable, str(extractor_script),
        str(run_dir),
        str(output_dir),
        "--protein-name", protein_name,
    ]
    if args.pae:
        cmd.append("--pae")

    if model_name == "boltz":
        if args.boltz_confidence:
            cmd.append("--confidence")
        if args.boltz_pde:
            cmd.append("--pde")
    elif model_name == "chai1":
        if args.chai_confidence:
            cmd.append("--confidence")
        if args.chai_contact_probs:
            cmd.append("--contact-probs")

    try:
        with open(log_file, 'w') as f:
            process = subprocess.run(
                cmd,
                check=True,
                capture_output=True,
                text=True,
                encoding='utf-8'
            )
            f.write("-- STDOUT --\n")
            f.write(process.stdout)
            f.write("\n-- STDERR --\n")
            f.write(process.stderr)
        logging.info(f"  Successfully ran {model_name} extractor. Log: {log_file}")
    except subprocess.CalledProcessError as e:
        logging.error(f"  Error running {model_name} extractor for {protein_name}.")
        logging.error(f"  Command: {' '.join(e.cmd)}")
        logging.error(f"  Return code: {e.returncode}")
        with open(log_file, 'a') as f:
            f.write("\n-- ERROR: Subprocess failed --\n")
            f.write("\n-- STDOUT --\n")
            f.write(e.stdout)
            f.write("\n-- STDERR --\n")
            f.write(e.stderr)
        logging.error(f"  See log for details: {log_file}")
    except FileNotFoundError:
        logging.error(f"  Extractor script not found: {extractor_script}")
        logging.error("  Please ensure this script is run from the 'abcfold/scripts' directory or that paths are correct.")


def extract_unique_files(run_dir: pathlib.Path, output_dir: pathlib.Path, protein_name: str):
    """
    Extract unique, important files from the run directory, like the input JSON
    and MSA depth plot, using a flexible search.
    
    Raises:
        FileNotFoundError: If the main _data.json file cannot be found.
    """
    logging.info(f"Extracting unique files for {protein_name}...")
    protein_output_dir = output_dir / protein_name
    protein_output_dir.mkdir(exist_ok=True)

    # --- Flexible JSON search with multiple strategies ---
    json_found = False
    
    # Find all *_data.json files recursively
    all_data_files = list(run_dir.rglob("*_data.json"))
    
    if all_data_files:
        # Strategy 1: Find exact match with protein name (best match)
        matching_files = [f for f in all_data_files if protein_name in f.name]
        
        if matching_files:
            # Prefer file with shortest path (closest to root), then by name
            src_json = min(matching_files, key=lambda p: (len(p.parts), p.name))
            dest_json = protein_output_dir / f"{protein_name}_data.json"
            shutil.copy2(src_json, dest_json)
            logging.info(f"  Copied {src_json.relative_to(run_dir)} to {dest_json}")
            json_found = True
        else:
            # Strategy 2: No exact match, try to find in model directories
            # Prefer files in alphafold3, then boltz, then chai1
            for model_prefix in ["alphafold3_", "boltz_", "chai1_"]:
                model_files = [f for f in all_data_files if model_prefix in str(f)]
                if model_files:
                    src_json = model_files[0]  # Take first from this model
                    dest_json = protein_output_dir / f"{protein_name}_data.json"
                    shutil.copy2(src_json, dest_json)
                    logging.info(f"  Copied {src_json.relative_to(run_dir)} to {dest_json} (using {model_prefix})")
                    json_found = True
                    break
            
    if not json_found:
        # Provide debug info about what files were found
        all_json_files = list(run_dir.rglob("*.json"))
        json_debug = f"Found {len(all_json_files)} total .json files"
        if all_json_files:
            sample_files = [f.name for f in all_json_files[:3]]
            json_debug += f" (e.g., {', '.join(sample_files)})"
        
        error_msg = (
            f"Could not find main input JSON file for {protein_name}. "
            f"Searched for *_data.json files matching protein name or in model directories (alphafold3, boltz, chai1). "
            f"{json_debug}"
        )
        logging.error(f"  {error_msg}")
        raise FileNotFoundError(error_msg)

    # --- PDF search for Chai1 MSA depth plot ---
    pdf_files = list(run_dir.glob(f"chai1_{protein_name}*/chai_output_seed-*/msa_depth.pdf"))
    if not pdf_files:
        # Try more flexible search
        pdf_files = list(run_dir.rglob("chai_output_seed-*/msa_depth.pdf"))
    
    if pdf_files:
        src_pdf = pdf_files[0]  # Grab from the first match
        dest_pdf = protein_output_dir / f"{protein_name}_msa_depth.pdf"
        shutil.copy2(src_pdf, dest_pdf)
        logging.info(f"  Copied msa_depth.pdf to {dest_pdf}")
    else:
        logging.info(f"  No msa_depth.pdf found for {protein_name} (normal if Chai1 was not run).")


def process_tarball(tarball: pathlib.Path, output_dir: pathlib.Path, args: argparse.Namespace):
    """
    Extracts a single ABCfold output tarball and runs the necessary extractors.
    """
    protein_name = get_protein_name_from_tarball(tarball)
    logging.info(f"\n{'='*60}\nProcessing {tarball.name} for protein {protein_name}\n{'='*60}")

    with tempfile.TemporaryDirectory(prefix=f"abcfold_{protein_name}_") as tmpdir:
        tmp_path = pathlib.Path(tmpdir)
        logging.info(f"Extracting tarball to temporary directory: {tmp_path}")
        try:
            with tarfile.open(tarball, "r:*") as tar:
                all_members = tar.getmembers()
                if not all_members:
                    logging.error(f"Tarball {tarball.name} is empty.")
                    return

                strip_val = args.strip_components
                if strip_val is None:
                    logging.info("`--strip-components` not provided, attempting to auto-detect.")
                    run_dir_name_from_tar = tarball.name.rsplit('.tar', 1)[0]
                    
                    base_dir_path = None
                    for member in all_members:
                        if member.isdir() and member.name.strip('/').endswith(run_dir_name_from_tar):
                            base_dir_path = member.name.strip('/')
                            break
                    
                    if base_dir_path:
                        strip_val = len(pathlib.Path(base_dir_path).parts) - 1
                        logging.info(f"  Auto-detected strip-components = {strip_val} (based on path '{base_dir_path}')")
                    else:
                        strip_val = 0
                        logging.warning(f"  Could not auto-detect strip value for '{run_dir_name_from_tar}'. Using 0.")
                        logging.warning("  You may need to provide --strip-components manually.")

                members_to_extract = []
                if strip_val > 0:
                    logging.info(f"Stripping {strip_val} path components during extraction.")
                    for member in all_members:
                        path_parts = list(pathlib.Path(member.path).parts)
                        if len(path_parts) > strip_val:
                            member.path = str(pathlib.Path(*path_parts[strip_val:]))
                            members_to_extract.append(member)
                else:
                    members_to_extract = all_members

                tar.extractall(path=tmp_path, members=members_to_extract)

        except tarfile.TarError as e:
            logging.error(f"Error extracting tarball {tarball.name}: {e}")
            return

        # The tarball contains a single directory with the run data
        extracted_dirs = [d for d in tmp_path.iterdir() if d.is_dir()]
        if not extracted_dirs:
            logging.error(f"Tarball {tarball.name} has an unexpected structure or is empty after extraction.")
            return
        run_dir = extracted_dirs[0]

        # Create a directory for logs for this specific run
        log_dir = output_dir / protein_name / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)

        # Run extractors for each model if its output directory exists
        for extractor in EXTRACTOR_SCRIPTS:
            model_name = extractor.parent.name
            if list(run_dir.glob(f"{model_name}_*")):
                log_file = log_dir / f"{protein_name}_{model_name}_extraction.log"
                run_extractor(extractor, run_dir, output_dir, protein_name, args, log_file)
            else:
                logging.info(f"No {model_name} output found for {protein_name}, skipping extractor.")

        # Extract unique files like the input JSON and plots
        try:
            extract_unique_files(run_dir, output_dir, protein_name)
        except FileNotFoundError as e:
            logging.error(f"Failed to extract required files for {protein_name}: {e}")
            raise

    logging.info(f"Finished processing {tarball.name}")


def process_tarball_wrapper(tarball_and_output: Tuple[pathlib.Path, pathlib.Path, argparse.Namespace]) -> Tuple[pathlib.Path, bool, str]:
    """
    Wrapper function to process a single tarball for use with ProcessPoolExecutor.
    
    Returns a tuple of (tarball_path, success, message).
    """
    tarball, output_dir, args = tarball_and_output
    try:
        process_tarball(tarball, output_dir, args)
        return (tarball, True, f"Successfully processed {tarball.name}")
    except FileNotFoundError as e:
        return (tarball, False, f"Failed to process {tarball.name}: {str(e)}")
    except Exception as e:
        return (tarball, False, f"Error processing {tarball.name}: {str(e)}")


def main():
    """Main function to parse arguments and orchestrate the extraction process."""
    parser = argparse.ArgumentParser(
        description="Compress and extract key outputs from ABCfold run tarballs.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--input-dirs",
        type=pathlib.Path,
        nargs="+",
        required=True,
        help="One or more directories containing the tarballs of ABCfold outputs."
    )
    parser.add_argument(
        "--output-dir",
        type=pathlib.Path,
        required=True,
        help="Directory where the compressed outputs will be saved."
    )
    parser.add_argument(
        "--strip-components",
        type=int,
        default=None,
        metavar="N",
        help="Strip N leading components from file names on extraction. "
             "If not provided, the script will try to auto-detect the value."
    )
    parser.add_argument(
        "--pae",
        action="store_true",
        help="Extract PAE matrices for all models. [default: False]"
    )
    parser.add_argument(
        "--boltz-confidence",
        action="store_true",
        help="Extract Boltz-specific confidence scores. [default: False]"
    )
    parser.add_argument(
        "--boltz-pde",
        action="store_true",
        help="Extract Boltz PDE matrices. [default: False]"
    )
    parser.add_argument(
        "--chai-confidence",
        action="store_true",
        help="Extract Chai-specific confidence scores. [default: False]"
    )
    parser.add_argument(
        "--chai-contact-probs",
        action="store_true",
        help="Extract Chai contact probabilities. [default: False]"
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=None,
        metavar="N",
        help="Number of parallel worker processes to use for processing tarballs. "
             "Default: number of CPU cores. Set to 1 to disable parallelization."
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging."
    )
    args = parser.parse_args()

    # Create the main output directory first
    args.output_dir.mkdir(parents=True, exist_ok=True)
    
    # Set up log file
    log_file = args.output_dir / "compression_run.log"
    
    setup_logging(args.verbose, log_file)

    # Check if extractor scripts are found
    if not all(EXTRACTOR_SCRIPTS):
        logging.error("Could not define extractor script paths. This script should be run from within the ABCfold project.")
        sys.exit(1)
    if not all(s.exists() for s in EXTRACTOR_SCRIPTS):
        logging.error("One or more extractor scripts not found. Checked paths:")
        for s in EXTRACTOR_SCRIPTS:
            logging.error(f"  - {s} (Exists: {s.exists()})")
        sys.exit(1)

    # Create the main output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Find and process all specified tarballs
    tarballs = find_tarballs(args.input_dirs)
    if not tarballs:
        logging.warning("No tarballs found in the specified input directories.")
        return

    logging.info(f"Found a total of {len(tarballs)} tarballs to process.")

    # Determine number of workers
    num_workers = args.workers
    if num_workers is None:
        num_workers = os.cpu_count() or 1
    
    if num_workers < 1:
        logging.error("Number of workers must be at least 1.")
        sys.exit(1)
    
    if num_workers == 1:
        logging.info("Processing tarballs sequentially (1 worker).")
        failed_tarballs = []
        for i, tarball in enumerate(tqdm(tarballs, desc="Processing tarballs", unit="tarball"), 1):
            try:
                process_tarball(tarball, args.output_dir, args)
                logging.info(f"[{i}/{len(tarballs)}] Successfully processed {tarball.name}")
            except FileNotFoundError as e:
                logging.error(f"[{i}/{len(tarballs)}] Failed to process {tarball.name}: {str(e)}")
                failed_tarballs.append((tarball.name, str(e)))
            except Exception as e:
                logging.error(f"[{i}/{len(tarballs)}] Error processing {tarball.name}: {str(e)}")
                failed_tarballs.append((tarball.name, str(e)))
        
        if failed_tarballs:
            logging.warning(f"\n{'='*60}\nProcessing completed with {len(failed_tarballs)} failure(s):\n{'='*60}")
            for tarball_name, error in failed_tarballs:
                logging.error(f"  - {tarball_name}: {error}")
            sys.exit(1)
    else:
        logging.info(f"Processing {len(tarballs)} tarballs in parallel with {num_workers} workers.")
        
        # Create a list of tasks for the executor
        tasks = [(tarball, args.output_dir, args) for tarball in tarballs]
        
        # Track failures
        failed_tarballs = []
        
        # Process tarballs in parallel
        with concurrent.futures.ProcessPoolExecutor(max_workers=num_workers) as executor:
            # Submit all tasks
            futures = {
                executor.submit(process_tarball_wrapper, task): task[0] 
                for task in tasks
            }
            
            # Collect results as they complete with progress bar
            completed = 0
            for future in tqdm(concurrent.futures.as_completed(futures), 
                             total=len(tarballs),
                             desc="Processing tarballs",
                             unit="tarball"):
                try:
                    tarball_path, success, message = future.result()
                    completed += 1
                    if success:
                        logging.info(f"[{completed}/{len(tarballs)}] {message}")
                    else:
                        logging.error(f"[{completed}/{len(tarballs)}] {message}")
                        # Extract error message for summary
                        error_msg = message.split(": ", 1)[1] if ": " in message else message
                        failed_tarballs.append((tarball_path.name, error_msg))
                except Exception as e:
                    completed += 1
                    logging.error(f"[{completed}/{len(tarballs)}] Unexpected error: {str(e)}")
                    failed_tarballs.append((futures[future].name, str(e)))
        
        if failed_tarballs:
            logging.warning(f"\n{'='*60}\nProcessing completed with {len(failed_tarballs)} failure(s):\n{'='*60}")
            for tarball_name, error in failed_tarballs:
                logging.error(f"  - {tarball_name}: {error}")
            sys.exit(1)

    logging.info(f"\n{'='*60}\nAll processing complete.\n{'='*60}")
    logging.info(f"Check the output directory: {args.output_dir}")
    
    # Print log file location to console since we only show errors there
    print(f"\n✓ Processing complete. Full log available at: {log_file}", file=sys.stderr)


if __name__ == "__main__":
    main()